FROM oven/bun:1 AS builder
WORKDIR /app
COPY package.json bun.lock tsconfig.json ./
RUN bun install
COPY prisma/schema.prisma ./prisma/schema.prisma
COPY src ./src
RUN bunx prisma generate
RUN bun run build

FROM oven/bun:1
WORKDIR /app
COPY --from=builder /app/package.json ./
COPY --from=builder /app/bun.lock ./
ENV NODE_ENV=production
RUN bun install --production
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["bun","run","start"]

